### ISSUE TITLE
Automatic dns push from resolvconf

### ISSUE THREAD

**Issue by ventre** [vemarsas/onboard#17]
If in the file / etc / network / interfaces the network interface remains set in dhcp, in Margay UI even if the network interface is configured as static the dns of the upstream modem remain set, I have solved adding the nameserver by shell :

dns-nameservers 208.67.222.123

evidence on margay desarlo.lagonegro

**Comment by gderosa** [comment]
onboard does not edit /etc/network/interfaces but it does override network config after boot, by design: this doesn't mean the config necessarily remains dhcp... it needs to be looked specifically. but the /etc/network/interfaces should not be the issue per se.
